# Country codes for Tor exit nodes

COUNTRY_CODES = {
    "US": "United States",
    "DE": "Germany",
    "NL": "Netherlands",
    "FR": "France",
    "GB": "United Kingdom",
    "SE": "Sweden",
    "CH": "Switzerland",
    "CA": "Canada",
    "FI": "Finland",
    "NO": "Norway",
    "DK": "Denmark",
    "AT": "Austria",
    "AU": "Australia",
    "JP": "Japan",
    "IT": "Italy",
    "RU": "Russia",
    "UA": "Ukraine",
    "PL": "Poland",
    "CZ": "Czech Republic",
    "ES": "Spain",
    "RO": "Romania",
    "BG": "Bulgaria",
    "TR": "Turkey",
    "BR": "Brazil",
    "SG": "Singapore",
    "HK": "Hong Kong",
    "IS": "Iceland",
    "LU": "Luxembourg",
    "LV": "Latvia",
    "EE": "Estonia",
    "LT": "Lithuania",
    "IE": "Ireland",
    "BE": "Belgium",
    "PT": "Portugal",
    "GR": "Greece",
    "HU": "Hungary",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "HR": "Croatia",
    "RS": "Serbia",
    "MK": "North Macedonia",
    "AL": "Albania",
    "ME": "Montenegro",
    "BA": "Bosnia and Herzegovina",
    "MD": "Moldova",
    "BY": "Belarus",
    "KR": "South Korea",
    "IN": "India",
    "ZA": "South Africa",
    "IL": "Israel",
    "MX": "Mexico",
    "AR": "Argentina",
    "CL": "Chile",
    "CO": "Colombia",
    "PE": "Peru",
    "VE": "Venezuela",
    "MY": "Malaysia",
    "TH": "Thailand",
    "ID": "Indonesia",
    "PH": "Philippines",
    "NZ": "New Zealand",
    "AE": "United Arab Emirates",
    "SA": "Saudi Arabia",
    "QA": "Qatar",
    "KW": "Kuwait",
    "BH": "Bahrain",
    "OM": "Oman",
    "JO": "Jordan",
    "LB": "Lebanon",
    "CY": "Cyprus",
    "MT": "Malta",
    "KZ": "Kazakhstan",
    "UZ": "Uzbekistan",
    "KG": "Kyrgyzstan",
    "TJ": "Tajikistan",
    "TM": "Turkmenistan",
    "MN": "Mongolia",
    "IR": "Iran",
    "IQ": "Iraq",
    "SY": "Syria",
    "EG": "Egypt",
    "MA": "Morocco",
    "DZ": "Algeria",
    "TN": "Tunisia",
    "LY": "Libya",
    "SD": "Sudan",
    "ET": "Ethiopia",
    "KE": "Kenya",
    "NG": "Nigeria",
    "GH": "Ghana",
    "SN": "Senegal",
    "CI": "Ivory Coast",
    "CM": "Cameroon",
    "UG": "Uganda",
    "TZ": "Tanzania",
    "MZ": "Mozambique",
    "ZW": "Zimbabwe",
    "AO": "Angola",
    "NA": "Namibia",
    "BW": "Botswana",
    "MU": "Mauritius",
    "SC": "Seychelles",
    "MV": "Maldives",
    "LK": "Sri Lanka",
    "NP": "Nepal",
    "BD": "Bangladesh",
    "PK": "Pakistan",
    "AF": "Afghanistan",
    "VN": "Vietnam",
    "KH": "Cambodia",
    "LA": "Laos",
    "MM": "Myanmar",
    "BN": "Brunei",
    "TW": "Taiwan",
    "MO": "Macau",
    "FJ": "Fiji",
    "PG": "Papua New Guinea",
    "NC": "New Caledonia",
    "PF": "French Polynesia",
    "WS": "Samoa",
    "TO": "Tonga",
    "VU": "Vanuatu",
    "SB": "Solomon Islands",
    "KI": "Kiribati",
    "FM": "Micronesia",
    "MH": "Marshall Islands",
    "PW": "Palau",
    "TV": "Tuvalu",
    "NR": "Nauru",
    "CK": "Cook Islands",
    "NU": "Niue",
    "TK": "Tokelau",
    "WF": "Wallis and Futuna",
    "AS": "American Samoa",
    "GU": "Guam",
    "MP": "Northern Mariana Islands",
    "PR": "Puerto Rico",
    "VI": "US Virgin Islands",
    "VG": "British Virgin Islands",
    "AI": "Anguilla",
    "AG": "Antigua and Barbuda",
    "BS": "Bahamas",
    "BB": "Barbados",
    "BZ": "Belize",
    "BM": "Bermuda",
    "KY": "Cayman Islands",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "SV": "El Salvador",
    "GD": "Grenada",
    "GT": "Guatemala",
    "HT": "Haiti",
    "HN": "Honduras",
    "JM": "Jamaica",
    "MQ": "Martinique",
    "MS": "Montserrat",
    "NI": "Nicaragua",
    "PA": "Panama",
    "KN": "Saint Kitts and Nevis",
    "LC": "Saint Lucia",
    "VC": "Saint Vincent and the Grenadines",
    "TT": "Trinidad and Tobago",
    "TC": "Turks and Caicos Islands",
    "UY": "Uruguay",
    "PY": "Paraguay",
    "BO": "Bolivia",
    "EC": "Ecuador",
    "GY": "Guyana",
    "SR": "Suriname",
    "GF": "French Guiana",
    "FK": "Falkland Islands",
    "GL": "Greenland",
    "PM": "Saint Pierre and Miquelon",
    "BL": "Saint Barthélemy",
    "MF": "Saint Martin",
    "SX": "Sint Maarten",
    "CW": "Curaçao",
    "AW": "Aruba",
    "BQ": "Caribbean Netherlands",
    "GI": "Gibraltar",
    "AD": "Andorra",
    "MC": "Monaco",
    "LI": "Liechtenstein",
    "SM": "San Marino",
    "VA": "Vatican City",
    "FO": "Faroe Islands",
    "AX": "Åland Islands",
    "SJ": "Svalbard and Jan Mayen",
    "GG": "Guernsey",
    "JE": "Jersey",
    "IM": "Isle of Man",
    "GS": "South Georgia and the South Sandwich Islands",
    "BV": "Bouvet Island",
    "HM": "Heard Island and McDonald Islands",
    "TF": "French Southern and Antarctic Lands",
    "IO": "British Indian Ocean Territory",
    "UM": "United States Minor Outlying Islands",
    "PS": "Palestine",
    "AQ": "Antarctica",
    "AZ": "Azerbaijan",
    "AM": "Armenia",
    "GE": "Georgia"
}

def get_country_name(country_code):
    """Returns the country name for a given country code."""
    return COUNTRY_CODES.get(country_code.upper(), "Unknown Country")

def get_all_countries():
    """Returns all country codes and names."""
    return COUNTRY_CODES

def get_popular_countries():
    """Returns popular country codes and names."""
    popular_codes = ["US", "DE", "NL", "FR", "GB", "SE", "CH", "CA", "FI", "NO"]
    return {code: COUNTRY_CODES[code] for code in popular_codes if code in COUNTRY_CODES}