# Country codes for Tor exit nodes

COUNTRY_CODES = {
    "US": "Amerika Birleşik Devletleri",
    "DE": "Almanya",
    "NL": "Hollanda",
    "FR": "Fransa",
    "GB": "Birleşik Krallık",
    "SE": "İsveç",
    "CH": "İsviçre",
    "CA": "Kanada",
    "FI": "Finlandiya",
    "NO": "Norveç",
    "DK": "Danimarka",
    "AT": "Avusturya",
    "AU": "Avustralya",
    "JP": "Japonya",
    "IT": "İtalya",
    "RU": "Rusya",
    "UA": "Ukrayna",
    "PL": "Polonya",
    "CZ": "Çek Cumhuriyeti",
    "ES": "İspanya",
    "RO": "Romanya",
    "BG": "Bulgaristan",
    "TR": "Türkiye",
    "BR": "Brezilya",
    "SG": "Singapur",
    "HK": "Hong Kong",
    "IS": "İzlanda",
    "LU": "Lüksemburg",
    "LV": "Letonya",
    "EE": "Estonya",
    "LT": "Litvanya",
    "IE": "İrlanda",
    "BE": "Belçika",
    "PT": "Portekiz",
    "GR": "Yunanistan",
    "HU": "Macaristan",
    "SK": "Slovakya",
    "SI": "Slovenya",
    "HR": "Hırvatistan",
    "RS": "Sırbistan",
    "MK": "Kuzey Makedonya",
    "AL": "Arnavutluk",
    "ME": "Karadağ",
    "BA": "Bosna Hersek",
    "MD": "Moldova",
    "BY": "Belarus",
    "KR": "Güney Kore",
    "IN": "Hindistan",
    "ZA": "Güney Afrika",
    "IL": "İsrail",
    "MX": "Meksika",
    "AR": "Arjantin",
    "CL": "Şili",
    "CO": "Kolombiya",
    "PE": "Peru",
    "VE": "Venezuela",
    "MY": "Malezya",
    "TH": "Tayland",
    "ID": "Endonezya",
    "PH": "Filipinler",
    "NZ": "Yeni Zelanda",
    "AE": "Birleşik Arap Emirlikleri",
    "SA": "Suudi Arabistan",
    "QA": "Katar",
    "KW": "Kuveyt",
    "BH": "Bahreyn",
    "OM": "Umman",
    "JO": "Ürdün",
    "LB": "Lübnan",
    "CY": "Kıbrıs",
    "MT": "Malta",
    "KZ": "Kazakistan",
    "UZ": "Özbekistan",
    "KG": "Kırgızistan",
    "TJ": "Tacikistan",
    "TM": "Türkmenistan",
    "MN": "Moğolistan",
    "IR": "İran",
    "IQ": "Irak",
    "SY": "Suriye",
    "EG": "Mısır",
    "MA": "Fas",
    "DZ": "Cezayir",
    "TN": "Tunus",
    "LY": "Libya",
    "SD": "Sudan",
    "ET": "Etiyopya",
    "KE": "Kenya",
    "NG": "Nijerya",
    "GH": "Gana",
    "SN": "Senegal",
    "CI": "Fildişi Sahili",
    "CM": "Kamerun",
    "UG": "Uganda",
    "TZ": "Tanzanya",
    "MZ": "Mozambik",
    "ZW": "Zimbabve",
    "AO": "Angola",
    "NA": "Namibya",
    "BW": "Botsvana",
    "MU": "Mauritius",
    "SC": "Seyşeller",
    "MV": "Maldivler",
    "LK": "Sri Lanka",
    "NP": "Nepal",
    "BD": "Bangladeş",
    "PK": "Pakistan",
    "AF": "Afganistan",
    "VN": "Vietnam",
    "KH": "Kamboçya",
    "LA": "Laos",
    "MM": "Myanmar",
    "BN": "Brunei",
    "TW": "Tayvan",
    "MO": "Makao",
    "FJ": "Fiji",
    "PG": "Papua Yeni Gine",
    "NC": "Yeni Kaledonya",
    "PF": "Fransız Polinezyası",
    "WS": "Samoa",
    "TO": "Tonga",
    "VU": "Vanuatu",
    "SB": "Solomon Adaları",
    "KI": "Kiribati",
    "FM": "Mikronezya",
    "MH": "Marshall Adaları",
    "PW": "Palau",
    "TV": "Tuvalu",
    "NR": "Nauru",
    "CK": "Cook Adaları",
    "NU": "Niue",
    "TK": "Tokelau",
    "WF": "Wallis ve Futuna",
    "AS": "Amerikan Samoası",
    "GU": "Guam",
    "MP": "Kuzey Mariana Adaları",
    "PR": "Porto Riko",
    "VI": "ABD Virgin Adaları",
    "VG": "İngiliz Virgin Adaları",
    "AI": "Anguilla",
    "AG": "Antigua ve Barbuda",
    "BS": "Bahamalar",
    "BB": "Barbados",
    "BZ": "Belize",
    "BM": "Bermuda",
    "KY": "Cayman Adaları",
    "CR": "Kosta Rika",
    "CU": "Küba",
    "DM": "Dominika",
    "DO": "Dominik Cumhuriyeti",
    "SV": "El Salvador",
    "GD": "Grenada",
    "GT": "Guatemala",
    "HT": "Haiti",
    "HN": "Honduras",
    "JM": "Jamaika",
    "MQ": "Martinik",
    "MS": "Montserrat",
    "NI": "Nikaragua",
    "PA": "Panama",
    "KN": "Saint Kitts ve Nevis",
    "LC": "Saint Lucia",
    "VC": "Saint Vincent ve Grenadinler",
    "TT": "Trinidad ve Tobago",
    "TC": "Turks ve Caicos Adaları",
    "UY": "Uruguay",
    "PY": "Paraguay",
    "BO": "Bolivya",
    "EC": "Ekvador",
    "GY": "Guyana",
    "SR": "Surinam",
    "GF": "Fransız Guyanası",
    "FK": "Falkland Adaları",
    "GL": "Grönland",
    "PM": "Saint Pierre ve Miquelon",
    "BL": "Saint Barthélemy",
    "MF": "Saint Martin",
    "SX": "Sint Maarten",
    "CW": "Curaçao",
    "AW": "Aruba",
    "BQ": "Karayip Hollandası",
    "GI": "Cebelitarık",
    "AD": "Andorra",
    "MC": "Monako",
    "LI": "Lihtenştayn",
    "SM": "San Marino",
    "VA": "Vatikan",
    "FO": "Faroe Adaları",
    "AX": "Åland Adaları",
    "SJ": "Svalbard ve Jan Mayen",
    "GG": "Guernsey",
    "JE": "Jersey",
    "IM": "Man Adası",
    "GS": "Güney Georgia ve Güney Sandwich Adaları",
    "BV": "Bouvet Adası",
    "HM": "Heard Adası ve McDonald Adaları",
    "TF": "Fransız Güney ve Antarktika Toprakları",
    "IO": "İngiliz Hint Okyanusu Toprakları",
    "UM": "ABD Küçük Dış Adaları",
    "PS": "Filistin",
    "AQ": "Antarktika",
    "AZ": "Azerbaycan",
    "AM": "Ermenistan",
    "GE": "Gürcistan"
}

def get_country_name(country_code):
    """Ülke koduna göre ülke adını döndürür."""
    return COUNTRY_CODES.get(country_code.upper(), "Bilinmeyen Ülke")

def get_all_countries():
    """Tüm ülke kodlarını ve isimlerini döndürür."""
    return COUNTRY_CODES

def get_popular_countries():
    """Popüler ülke kodlarını ve isimlerini döndürür."""
    popular_codes = ["US", "DE", "NL", "FR", "GB", "SE", "CH", "CA", "FI", "NO"]
    return {code: COUNTRY_CODES[code] for code in popular_codes if code in COUNTRY_CODES}